// 인증 이벤트 패턴
export const AUTH_EVENT_TYPE = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
};

// 이벤트 이벤트 패턴
export const EVENT_EVENT_TYPE = {
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  GET_ALL_EVENTS: 'GET_ALL_EVENTS',
  GET_EVENT_BY_ID: 'GET_EVENT_BY_ID',
};

// 리워드 이벤트 패턴
export const REWARD_EVENT_TYPE = {
  CREATE_REWARD: 'CREATE_REWARD',
  GET_REWARDS_BY_EVENT_ID: 'GET_REWARDS_BY_EVENT_ID',
  UPDATE_REWARD: 'UPDATE_REWARD',
  DELETE_REWARD: 'DELETE_REWARD',
  CREATE_REWARD_REQUEST: 'CREATE_REWARD_REQUEST',
  GET_REWARD_REQUESTS_BY_USER_ID: 'GET_REWARD_REQUESTS_BY_USER_ID',
  GET_ALL_REWARD_REQUESTS: 'GET_ALL_REWARD_REQUESTS',
  APPROVE_REWARD_REQUEST: 'APPROVE_REWARD_REQUEST',
  REJECT_REWARD_REQUEST: 'REJECT_REWARD_REQUEST',
};
